[DEFAULT]
RUN_NAME = ${JOB_NAME}

%include inis/modules.ini
%include inis/camb.ini

[pipeline]
modules = consistency camb_background sample_rdh desi_sdss
priors = 
values = inis/%(RUN_NAME)s_values.ini
extra_output = cosmological_parameters/sigma_8
; debug = False
; timing = False