[emcee]
walkers = 192
; This many samples is overkill, just to make the plots
; look a lot nicer
samples = 2000
; This is the interval at which convergence diagnostics
; are performed
nsteps = 10

[nautilus]
n_live = 4000
resume = False
verbose = False
filepath = output_pub/%(RUN_NAME)s_nautilus_checkpoints.hdf5
discard_exploration = True

[polychord]
base_dir = output/%(RUN_NAME)s_polychord_checkpoints
polychord_outfile_root = %(RUN_NAME)s
resume = F
feedback = 3
fast_fraction = 0.1

;Minimum settings
; live_points = 250
; num_repeats = 30
; tolerance = 0.1
live_points = 500
num_repeats = 20
tolerance = 0.1

;Settings for paper runs
; live_points = 500
; num_repeats = 60
; tolerance = 0.01
; boost_posteriors = 10.0