[DEFAULT]
RUN_NAME = ${JOB_NAME}

%include inis/modules.ini
%include inis/camb.ini

[pipeline]
modules = consistency camb_background des_sn5yr desi_sdss sample_rdh
priors =
values = inis/%(RUN_NAME)s_values.ini
extra_output =
; debug = False
; timing = False